spring.application.name=childcare-facilities-system


spring.data.mongodb.database=childcare_facilities
spring.data.mongodb.host=localhost
spring.data.mongodb.port=3308

# App Properties
bezkoder.app.jwtCookieName= bezkoder
bezkoder.app.jwtSecret= ======================BezKoder=Spring===========================
bezkoder.app.jwtExpirationMs= 86400000


springdoc.api-docs.path=/api/docs